version: '2'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - '444:443'

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
    - '443:443'
    - '80:80'
