FROM ubuntu:20.04 AS python2wayssl_base

LABEL maintainer="A python backend SSL enabled API server"

### bootstrap Ubuntu
ENV DEBIAN_FRONTEND=noninteractive \
    TZ=Asia/Shanghai
# update ubuntu
RUN apt-get update && \
    apt-get install -y --no-install-recommends software-properties-common openssh-server supervisor less vim sudo systemd traceroute wget curl libssl-dev locales tzdata python3-pip tcpdump &&\
    mkdir -p /var/run/sshd && \
    #setup supervisord
    mkdir -p /mnt/transient/log/supervisord && \
    #setup root password & config sshd service
    echo 'root:root' | chpasswd && \
    sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    # 设置时区
    ln -fs /usr/share/zoneinfo/$TZ /etc/localtime && \
    echo $TZ > /etc/timezone && \
    # 设置locale
    sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen && \
    locale-gen && \
    update-locale LANG=en_US.UTF-8 && \
    update-locale LC_ALL=en_US.UTF-8 && \
    update-locale LC_CTYPE=en_US.UTF-8 && \
    rm -rf /var/lib/apt/lists/*

# 添加 deadsnakes PPA（包含 Python 3.12）
RUN add-apt-repository ppa:deadsnakes/ppa -y && \
    apt-get update

# 安装 Python 3.12 和 pip
RUN apt-get install -y --no-install-recommends \
    python3.12 \
    python3.12-dev \
    python3.12-venv \
    python3.12-distutils \
    && rm -rf /var/lib/apt/lists/*

# 确保 pip 可用
RUN curl -sS https://bootstrap.pypa.io/get-pip.py | python3.12

# 设置 python3.12 为默认 python3
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.12 1

# 验证安装
RUN python3 --version && pip --version


#RUN wget \
#    https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
#    && mkdir /root/.conda \
#    && bash Miniconda3-latest-Linux-x86_64.sh -b \
#    && rm -f Miniconda3-latest-Linux-x86_64.sh \
#    && echo PATH="/root/miniconda3/bin":$PATH >> .bashrc \
#    && exec bash \
#    && conda --version \
#    && conda create -y -n myenv python=3.12 \
#    && echo "conda activate myenv" >> .bashrc \

# Expose SSH port
EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]

FROM python2wayssl_base AS py2wayssl

COPY ./supervisord/supervisord.conf /etc/supervisor/supervisord.conf

### setup and install API server app
RUN mkdir -p /mnt/app/demoapiserver
RUN mkdir -p /mnt/transient/log/app

ADD ./server/setup.py /mnt/app/demoapiserver
ADD ./server/requirements.txt /mnt/app/demoapiserver
ADD ./server/demoapiserver /mnt/app/demoapiserver/demoapiserver

# install
WORKDIR /mnt/app/demoapiserver
#RUN pip install .

### execute supervisor
#ENTRYPOINT ["supervisord", "-c","/etc/supervisor/supervisord.conf"]

# 保持容器运行的入口点
ENTRYPOINT ["/bin/bash", "-c", "service ssh start && tail -f /dev/null"]